### ISSUE TITLE
Format of sinceDate

### ISSUE THREAD

**Issue by bgewehr** [stefanopog/node-red-contrib-ibmconnections#1]
Whenever I use the sinceDate I get no more updates from the activity stream. I wanted to achieve a periodic poll of the stream and then act on the result, like a webhook listener (but there is none, right?). But with a given date I never get any result. How should the msg.sinceDate be formatted to work properly?

Currently I use "2018-01-24" as the time string which does not throw an error.

**Comment by stefanopog** [comment]
Have you tried the format 24/01/2018 ?
You could even specify a "time" : 24/01/2018T12:13:27
Pls let me know

**Comment by bgewehr** [comment]
I’m going to try that. The thing is that I obviously need to set that time in the inbound msg for that node. I’m sure to have tried all possible combinations but will try again with this one.
