### ISSUE TITLE
Community Activities have different terms

### ISSUE THREAD

**Issue by paulswithers** [stefanopog/node-red-contrib-ibmconnections#16]
It could be "explicit_membership_community_activity" or just "community_activity". This can be fixed by changing https://github.com/stefanopog/node-red-contrib-ibmconnections/blob/master/IBMConnections2/ICActivities.js#L826 to:
`if (tmp.term.indexOf("community_activity") > -1) processIt = true;`

**Comment by stefanopog** [comment]
Fixed in the next Commit
