### ISSUE TITLE
Unable to install 1.3.1 in Node Red / Bluemix

### ISSUE THREAD

**Issue by ManfredMeise** [stefanopog/node-red-contrib-ibmconnections#3]
Hi Stefano,

I am not able to install this package. How can I find out why and resolve the issue?

Manfred

**Comment by stefanopog** [comment]
Sorry, I slipped this ... Were you able to succesfully install it ? Now, most recent version is 1.3.7

**Comment by ManfredMeise** [comment]
Yes, after increasing memory assignment to 640MB....
