### ISSUE TITLE
getActivities for "Community Activities" doesn't filter on Community ID

### ISSUE THREAD

**Issue by paulswithers** [stefanopog/node-red-contrib-ibmconnections#8]
The ICActivities.html allows selection of a Community ID, but the logic in ICActivities.js lines 886 onwards doesn't use it. The URL used is always "/activities/service/atom2/activities?includeCommunityActivities=only" - including all community activities. That's valid if no community ID is entered, but otherwise it should be "/activities/service/atom2/activities?commUuid=" + the entered community ID.

**Comment by stefanopog** [comment]
Included
